[package]
name = "kernel_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9" # needed to follow the blog

# disable stack unwinding for both build options
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
